### ISSUE TITLE
Need to specify use of default function

### ISSUE THREAD

**Issue by jerseygooner** [electricmonk/sinon-chai-in-order#1]
Hi there! First off, super excited to come across this, on the very day I realized I needed a solution for this boom, you create this repo :+1: Thanks!

I am using the following versions of chai/sinon: 

```
    "sinon": "~1.10.3",
    "sinon-chai": "~2.6.0",
    "chai-as-promised": "~4.1.1",
    "sinon-chai-in-order": "0.0.1",
```

In order to extend chai, I need to call: 
`chai.use(sinonChaiInOrder.default);`

**Comment by electricmonk** [comment]
Hmm. I was under the impression that the fact that I'm publishing the module in UMD format should deal with that. Javascript is still a new and bizarre world for me :-)
I'll update the docs. Thanks!

**Comment by electricmonk** [comment]
Also, @jerseygooner - I would love to see how you use this library and hear some feedback.
